language: go
sudo: required
go_import_path: cirello.io/dynamolock
go:
  - "1.11"

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls
  - go mod download

install: true

script:
  - docker run -d -p 8000:8000 dwmkerr/dynamodb
  - go test -covermode=count -coverprofile=profile.cov -v ./...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci